baseurl = "http://bourbonwedding.github.io/"
languageCode = "en-us"
title = "Matt and Andrea - Oct 1, 2016"
theme = "bw-reponsive"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
disqusShortname = "arresteddevops"
archetypedir = "archetypes"
[permalinks]
	page = "/:filename/"
